import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.amBackground,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  section: {
    marginBottom: 28,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.amCard,
    padding: 16,
    borderRadius: 12,
    minHeight: 52,
  },
  rowLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.amWhite,
  },
  rowHint: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 8,
    marginLeft: 4,
  },
  infoCard: {
    backgroundColor: colors.amCard,
    padding: 16,
    borderRadius: 12,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.amWhite,
  },
  infoText: {
    fontSize: 14,
    color: colors.textMuted,
    marginTop: 8,
    lineHeight: 20,
  },
  storageCard: {
    backgroundColor: colors.amCard,
    padding: 16,
    borderRadius: 12,
  },
  storageLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.amWhite,
  },
  progressTrack: {
    height: 8,
    backgroundColor: colors.border,
    borderRadius: 4,
    marginTop: 12,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  storageHint: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 8,
  },
  storageWarning: {
    fontSize: 13,
    color: colors.amDanger,
    marginTop: 8,
    fontWeight: '500',
  },
  vaultInfoGrid: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 8,
  },
  vaultInfoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vaultInfoLabel: {
    fontSize: 13,
    color: colors.textMuted,
  },
  vaultInfoValue: {
    fontSize: 13,
    color: colors.amWhite,
    fontWeight: '500',
  },
  integrityButton: {
    backgroundColor: colors.amDeep,
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
    borderWidth: 1,
    borderColor: colors.amAmber,
    minHeight: 48,
    justifyContent: 'center',
  },
  integrityButtonDisabled: {
    opacity: 0.6,
  },
  integrityButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.amAmber,
  },
  corruptedHint: {
    fontSize: 13,
    color: colors.amDanger,
    marginTop: 8,
  },
  dangerButton: {
    backgroundColor: colors.amCard,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.amDanger,
    minHeight: 56,
  },
  dangerButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.amDanger,
  },
  dangerButtonHint: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
  },
  kitWarningCard: {
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    backgroundColor: colors.amCard,
  },
  kitWarningText: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  kitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.amCard,
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    minHeight: 64,
  },
  kitButtonIcon: {
    fontSize: 28,
    marginRight: 14,
  },
  kitButtonContent: {
    flex: 1,
  },
  kitButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.amWhite,
  },
  kitButtonHint: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  subscriptionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  subscriptionLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.amWhite,
  },
  subscriptionValue: {
    fontSize: 16,
    fontWeight: '700',
  },
  upgradeButton: {
    backgroundColor: colors.amAmber,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 8,
    minHeight: 48,
    justifyContent: 'center',
  },
  upgradeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.amBackground,
  },
  restorePurchasesButton: {
    padding: 10,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  restorePurchasesText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  lifetimeUpgradeCard: {
    backgroundColor: 'rgba(201,150,58,0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(201,150,58,0.35)',
    padding: 16,
    marginTop: 10,
    marginBottom: 2,
  },
  lifetimeUpgradeTop: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  lifetimeUpgradeBadge: {
    backgroundColor: colors.amAmber,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 5,
  },
  lifetimeUpgradeBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.amBackground,
    letterSpacing: 0.4,
  },
  lifetimeUpgradeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.amWhite,
    marginBottom: 4,
  },
  lifetimeUpgradeBody: {
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 18,
    marginBottom: 8,
  },
  lifetimeUpgradeCTA: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.amAmber,
  },
  premiumBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  premiumBadgeIcon: {
    fontSize: 14,
    color: colors.success,
    fontWeight: '700',
  },
  premiumBadgeLabel: {
    fontSize: 13,
    color: colors.textMuted,
    flex: 1,
  },
  backupWarning: {
    fontSize: 13,
    color: colors.amDanger,
    marginTop: 8,
  },
  backupDate: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 8,
  },
  backupActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  backupActionButton: {
    flex: 1,
    backgroundColor: colors.amDeep,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.amAmber,
    minHeight: 44,
    justifyContent: 'center',
  },
  backupActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.amAmber,
  },
  devRow: {
    backgroundColor: colors.amCard,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    minHeight: 56,
  },
  devRowText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.amWhite,
  },
  devRowHint: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
  },
});
